### ISSUE TITLE
Citations reference wrong year?

### ISSUE THREAD

**Issue by KyleHaynes** [ropensci/bomrang#72]
Just a FYI - your citations reference 2017. Not sure if you care or not ...

Quick search across the repo will highlight them (generally in readme.md)

**Comment by adamhsparks** [comment]
Did you mean this?

 To cite *bomrang*, please use:

        Adam H Sparks, Mark Padgham, Hugh Parsonage and Keith Pembleton (2017).
        bomrang: Fetch Australian Government Bureau of Meteorology Weather Data.
        The Journal of Open Source Software, 2(17).
        DOI: [10.21105/joss.00411](https://doi.org/10.21105/joss.00411)

That should be 2017, as that's when the paper was published.

Or the examples? I didn't want to bother regenerating new examples for the README. The values change but not the contents.

Or something else that I'm missing? I'm not clear here on what the issue is.

**Comment by KyleHaynes** [comment]
Sorry, I'm a fool. There were a few instances, but yes, I mainly meant the paper (which I'm totally wrong about)

**Comment by adamhsparks** [comment]
No apology necessary. Always good to get feedback, I/we do miss things from time-to-time.
