### ISSUE TITLE
Non-current stations unavailable from get_historical

### ISSUE THREAD

**Issue by mbertolacci** [ropensci/bomrang#81]
It appears that `get_historical` only recognises stations that are still current, rather than all historical stations. For instance, the following line fails with 'Error: Station not recognised':

```
bomrang::get_historical('068016')
```

but this station actually has data at http://www.bom.gov.au/climate/data/.

Looking at https://github.com/ropensci/bomrang/blob/master/data-raw/create_BOM_station_list.Rmd suggests this is because the internal station list is filtered to current sites.

Perhaps instead the internal list could store all stations, with a flag representing currentness?

**Comment by jonocarroll** [comment]
I tagged you in because I'm not sure if the station list code tracks older stations. If you need me to make adjustments in `get_historical` then I'm certainly happy to do so.

**Comment by mbertolacci** [comment]
One thing that's worth noting is that different stations have historical data for different product types. For instance, 68016 has historical rainfall data, but doesn't appear to have max temperature data.

In my own package [bomdata](https://github.com/mbertolacci/bomdata) (which I am probably going to simplify/change now that bomrang is out and when/if this issue is fixed), I use the URL http://www.bom.gov.au/climate/data/lists_by_element/alphaAUS_136.txt to determine which sites have historical rainfall data, and that appears to work for different codes like 122 for max temp.

**Comment by jonocarroll** [comment]
That looks very useful for populating a station database. Cheers!

@adamhsparks I'm happy to switch around the station-processing parts of `get_historical` to scan this data too, or we could cache it, ...

**Comment by adamhsparks** [comment]
Thanks for the additional info, @mbertolacci. Let me have a look at what it will take. Modifying the internal database has a flow-on effect to more than one function in `bomrang`. @jonocarroll, this may take both of us to get it fixed I think. I'll need to see what needs to be done constructing the database. Off the top of my head, maybe I can just generate a new database that includes all of the historical, non-operational stations and we use that for `get_historical`.

**Comment by adamhsparks** [comment]
Well, phooey. I thought I had a fix for this but I guess not. Apparently the example station does not fit the method that we've used for determining what stations have a valid JSON file URL to retrieve data from, which is what the `get_historical()` is currently using.

I tried the easy route to just not remove stations that are not current since I thought that this would fix the issue. However, this didn't fix the issue, at least for the example station. It only netted a few more stations back to ~2010 at the latest. We need a different approach since the quick and easy won't fix it.

I'm open to suggestions, maybe there are more pages like http://www.bom.gov.au/climate/data/lists_by_element/alphaAUS_136.txt that can be used for more than just rainfall? In that case I suggest a new .Rmd in `data-raw` and new internal DB that uses these files to generate a DB just for the `get_historical()` function since it seems the current one isn't as useful as it could be for this purpose.

I've managed to address a bunch of other things today by working on this, but not this one as I'd hoped when I started. So at least I have that going for me.

**Comment by mbertolacci** [comment]
Nice work, yes, it's pretty complicated! In the URL http://www.bom.gov.au/climate/data/lists_by_element/alphaAUS_136.txt the 136 corresponds to the daily rainfall product. That's the nccObsCode that goes into climate data URLs. The other nccObsCode values are:

- Max temp = 122
- Min temp = 123
- Solar exposure = 193

Sites also have different p_c codes for different values of nccObsCode so that needs to be taken into account if you are caching the p_c codes.

I imagine a straightforward implementation of a database would be to have two columns, station number and nccObsCode. Instead of querying the database by station number in get_historical, query with the tuple (station number, nccObsCode).

**Comment by adamhsparks** [comment]
Ah, thanks, that's exactly what I was needing.

**Comment by adamhsparks** [comment]
I've just pushed a new commit that is my first attempt at addressing this Issue.

@jonocarroll, would you please look over what I've done to your function and let me know what you think?

I've incorporated functionality to download the metadata from BOM as @mbertolacci suggested. Then function checks for the station in the list and the data availability for the station.

Alternatively the user may also request to have the metadata for the station and data returned as well. This is done by returning a list with a `data.frame` of metadata and then the main `data.frame` of historical data. The argument in `get_historical()`, `meta` is set to FALSE so only a `data.frame` of weather data is returned by default.

I chose not to use the data-raw approach because BOM is updating the metadata frequently and thought that users might want access to this as well. It also only adds ~0.5sec to runtime depending on the connectivity, not as much as downloading the actual data by far.

Thoughts?

**Comment by adamhsparks** [comment]
I've written tests and documentation for this. Everything seems to be working well, so I'm going to close this issue now and release the updated version of `bomrang`.

Please feel free to open a new issue if something new arises out of this.

**Comment by jonocarroll** [comment]
Argh! I'm overseas for work at the moment and had this in my priority inbox to have a look at sometime... then I hear it's merged and released. Sorry. I do trust you to have handled it nicely but I'll have a look through nonetheless.

**Comment by adamhsparks** [comment]
@jonocarroll, sorry mate! I figured you'd had a look since I hadn't heard anything back from you. My mistake, I should have waited a bit longer. It took me long enough to get around to it.

I'm rethinking my handling with the `meta` argument, but I don't have a good suggestion for how to handle it other than how I have now, so if you have something I'm happy to hear it.

**Comment by jonocarroll** [comment]
I will definitely have a look.
